### ISSUE TITLE
Firebase deployment

### ISSUE THREAD

**Issue by jstnceronio** [jstnceronio/gibb-marketplace#48]

**Comment by Akjo03** [comment]
@jstnceronio @RoadJDK @alineammann @Akjo03 **gibbMarketplace is now deployed on https://gibb-marketplace.firebaseapp.com!**

Also use `npm run serve` now instead of `npm start`. To deploy do `npm run deploy`!

**Comment by Akjo03** [comment]
Also see https://github.com/jstnceronio/gibb-marketplace/blob/main/DEPLOY.md
